# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7ad09549b79f0279bc8117b6b89d43cb661529a2c2f6832eb07a8e27ad84349c0823ac29bdc6327c739eb534a95a7dfea3533e940c737875721e816017d642c

test:
  secret_key_base: 0358cbca3881e44f550f92a4e7be92fa5de1e9838f07cabe104265402c218c8d07e4fe8436e8d1f53af08cfabf25489dea7f70ca832a52e727eb92777aa938bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
